### ISSUE TITLE
Create an official Meteor wrapper for Stampit

### ISSUE THREAD

**Issue by ericelliott** [stampit-org/stampit-meteor#1]
cc @yasinuslu @philcockfield

**Comment by ericelliott** [comment]
See also: https://github.com/stampit-org/stampit/issues/138

**Comment by yasinuslu** [comment]
I am volunteering to maintain this package.

**Comment by ericelliott** [comment]
:+1:

**Comment by yasinuslu** [comment]
Thank you for invitation

**Comment by koresar** [comment]
So, was it published?

**Comment by yasinuslu** [comment]
Yes it's published https://atmospherejs.com/stampitorg/stampit

**Comment by koresar** [comment]
That was fast. Thanks Yasin.

**Comment by yasinuslu** [comment]
No problem :)

**Comment by ericelliott** [comment]
Nice.
